float convertLength(float value, int fromUnit, int toUnit);
void printLengthMenu();
float convertMass(float value, int fromUnit, int toUnit);
void printMassMenu();
float convertVolume(float value, int fromUnit, int toUnit);
void printVolumeMenu();
float convertTemp(float value, int fromUnit, int toUnit);
void printTempMenu();
float convertTime(float value, int fromUnit, int toUnit);
void printTimeMenu();
void printMenu();